'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5420
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TPS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property access() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("access", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property adelante() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adelante", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property atras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property barra1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barra1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property barra2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barra2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boton2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boton3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boton4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boton5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eliminar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eliminar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guardar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guardar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imprimir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imprimir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property informe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("informe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property infosys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("infosys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inventario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inventario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nuevo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nuevo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property primero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("primero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property respaldo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("respaldo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property respaldocd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("respaldocd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sql() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sql", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ultimo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ultimo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
